[package]
name = "video_capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linuxvideo = "0.3.0"
anyhow = "1.0.68"
env_logger = { version = "0.10.0", default-features = false }

