[package]
name = "video-capture"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "V4L2 video capture"
repository = "https://github.com/ichergui/video-capture"
keywords = ["linux", "video", "webcam"]

[dependencies]
h264_webcam_stream = "0.1.0"
anyhow = "1.0.68"
